{
 "title": "ProgIngInf PUE",
 "description": "Progetto di Ingegneria Informatica: Calculating PUE for the deib server room using reported UPS inputs and PDU data.",
 "time": { "from": "2025-07-21T20:30:00.000Z", "to": "2025-07-23T20:30:00.000Z" },
 "panels": [
  {
   "title": "PUE",
   "type": "timeseries",
   "description": "ALL UPS / ALL PDU",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expression": "$ups/$PDU", "type": "math" }
   ]
  },
  {
   "title": "UPS Output",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    { "expr": "lcUpsOutputWatts", "legendFormat": "__auto" },
    {
     "expr": "lgpPwrMeasurementPointTruePower",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PDU Input",
   "type": "timeseries",
   "description": "Total input power for all power supply units.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    { "expr": "sum(lgpPduPsEntryPwrTotal)", "legendFormat": "__auto" }
   ]
  }
 ]
}