{
 "title": "Sala Macchine",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Potenza effettiva per PDU",
   "type": "bargauge",
   "description": "MT/Diff tarati a 6.3 kW",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "lgpPduPsEntryPwrTotal", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Temperature Chiller",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "lgpEnvTemperatureMeasurementTenthsDegC{lgpEnvTemperatureIdDegC=\"7\"}/10",
     "legendFormat": "Acqua raffreddamento {{instance}}"
    },
    {
     "expr": "lgpEnvTemperatureMeasurementTenthsDegC{lgpEnvTemperatureIdDegC=\"1\"}/10",
     "legendFormat": "Aria fredda (uscita) {{instance}}"
    },
    {
     "expr": "lgpEnvTemperatureMeasurementTenthsDegC{lgpEnvTemperatureIdDegC=\"2\"}/10",
     "legendFormat": "Aria calda (entrata) {{instance}}"
    }
   ]
  },
  {
   "title": "Potenza totale",
   "type": "gauge",
   "description": "60 kVA (cosfi 0.9)",
   "gridPos": { "h": 8, "w": 5, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(lgpPduPsEntryPwrTotal)", "legendFormat": "Somma Pot. PDU" },
    {
     "expr": "lgpPwrMeasurementPointTruePower",
     "legendFormat": "Potenza misurata UPS"
    }
   ]
  },
  {
   "title": "Tensioni LL Ingresso UPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "lgpPwrLineMeasurementVoltsLL{lgpPwrMeasurementPtIndex=\"3\"}",
     "legendFormat": "Misura {{lgpPwrLineMeasurementIndex}}"
    }
   ]
  },
  {
   "title": "Correnti Ingresso UPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "expr": "lgpPwrLineMeasurementCurrent{lgpPwrMeasurementPtIndex=\"3\"}",
     "legendFormat": "Corrente fase {{lgpPwrLineMeasurementIndex}}"
    }
   ]
  },
  {
   "title": "Tensioni UPS",
   "type": "timeseries",
   "description": "Scraping UPS",
   "gridPos": { "h": 8, "w": 8, "x": 14, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "lgpPwrLineMeasurementVoltsLN{lgpPwrMeasurementPtIndex=\"1\"}",
     "legendFormat": "Uscita UPS Fase {{lgpPwrLineMeasurementIndex}}"
    },
    {
     "expr": "lgpPwrLineMeasurementVoltsLN{lgpPwrMeasurementPtIndex=\"2\"}",
     "legendFormat": "Bypass UPS Fase {{lgpPwrLineMeasurementIndex}}"
    },
    {
     "expr": "lgpPwrLineMeasurementVoltsLN{lgpPwrMeasurementPtIndex=\"3\"}",
     "legendFormat": "Ingresso UPS Fase {{lgpPwrLineMeasurementIndex}}"
    },
    { "expr": "lcUpsInputVoltage", "legendFormat": "Ingresso UPS Piano 1" },
    { "expr": "lcUpsOutputVoltage", "legendFormat": "Uscita UPS Piano 1" }
   ]
  },
  {
   "title": "Temperature sensori rack",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "lgpEnvRemoteSensorTempMeasurementDegC",
     "legendFormat": "Rack {{lgpEnvRemoteSensorUsrLabel}}"
    }
   ]
  },
  {
   "title": "Temperature Chiller",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "lgpEnvTemperatureMeasurementTenthsDegC{lgpEnvTemperatureIdDegC=\"7\"}/10",
     "legendFormat": "Acqua raffreddamento {{instance}}"
    },
    {
     "expr": "lgpEnvTemperatureMeasurementTenthsDegC{lgpEnvTemperatureIdDegC=\"1\"}/10",
     "legendFormat": "Aria fredda (uscita) {{instance}}"
    },
    {
     "expr": "lgpEnvTemperatureMeasurementTenthsDegC{lgpEnvTemperatureIdDegC=\"2\"}/10",
     "legendFormat": "Aria calda (entrata) {{instance}}"
    },
    {
     "expr": "lgpFlexibleEntryIntegerValue{lgpFlexibleEntryDataLabel=\"Supply Air Temperature\",lgpFlexibleEntryIndex=\"0x0102018A\"}/10",
     "legendFormat": "{{label_name}} Aria fredda (piano 1)"
    },
    {
     "expr": "lgpFlexibleEntryIntegerValue{lgpFlexibleEntryDataLabel=\"Return Air Temperature\",lgpFlexibleEntryIndex=\"0x010201C3\"}/10",
     "legendFormat": "{{label_name}} Aria calda (piano 1)"
    }
   ]
  },
  {
   "title": "Livello di umidità",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "expr": "lgpEnvHumidityMeasurementRelTenths{lgpEnvHumidityIdRel=\"1\"}/10",
     "legendFormat": "{{instance}} - return"
    },
    {
     "expr": "lgpEnvHumidityMeasurementRelTenths{lgpEnvHumidityIdRel=\"2\"}/10",
     "legendFormat": "{{instance}} - supply"
    }
   ]
  },
  {
   "title": "Storico Consumo istantaneo",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    { "expr": "sum(lgpPduPsEntryPwrTotal)", "legendFormat": "Somma potenza PDU" },
    {
     "expr": "lgpPwrMeasurementPointTruePower ",
     "legendFormat": "Potenza misurata UPS"
    },
    { "expression": "$B - $A", "type": "math" }
   ]
  },
  {
   "title": "Tensione per PDU",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 11, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    { "expr": "lgpPduPsLineEntryEpLNTenths/10", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Potenza effettiva per PDU",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 11, "x": 11, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    { "expr": "lgpPduPsEntryPwrTotal", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Potenza apparente per PDU",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 11, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    { "expr": "lgpPduPsEntryApTotal", "legendFormat": "{{instance}}" },
    {}
   ]
  },
  {
   "title": "Statistiche ventole",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 11, "x": 11, "y": 45 },
   "targets": [
    { "expr": "lgpEnvStateFanCapacity", "legendFormat": "Ventole Chiller {{instance}}" },
    {
     "expr": "lgpFlexibleEntryUnsignedIntegerValue{lgpFlexibleEntryDataLabel=\"Condenser Fan Speed\"}",
     "legendFormat": "Ventole Chiller P1-1"
    }
   ]
  },
  {
   "title": "Durata residua batteria UPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    { "expr": "lcUpsBatTimeRemaining", "legendFormat": "Primo Piano" },
    { "expr": "lgpPwrBatteryTimeRemaining", "legendFormat": "Seminterrato" }
   ]
  },
  {
   "title": "PUE",
   "type": "timeseries",
   "description": "60 kVA (cosfi 0.9)",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expression": "($Total+7)/$Sum_PDU", "type": "math" }
   ]
  }
 ]
}