---
auths:
  main_community:
    version: 2
    community: monitor127
  main_community_cotto:
    version: 2
    community: ENPRackPDU_RO


# Liebert/Vertiv PDU's
#
# https://www.vertiv.com/en-us/support/software-download/monitoring/management-information-bases-mibs-for-liebert-products/
# https://www.vertiv.com/492204/contentassets/b00273585e0a453a9c983523e8a0d6ff/lgpmib-unix_rev16.tar
modules:
  liebert_pdu:
    walk:
      - sysName
      - sysDescr
      - sysUpTime
      - lgpPduTable
      - lgpPduPsTable
      - lgpPduPsLineTable
      - lgpPduRcpTable
      - lgpPduAuxSensorTable
      - lgpConditionsWellKnown
      - lgpEnvTemperatureWellKnown
    lookups:
      - source_indexes: [lgpPduEntryIndex]
        lookup: lgpPduEntrySysAssignLabel
      - source_indexes: [lgpPduPsEntryIndex]
        lookup: lgpPduPsEntrySysAssignLabel
      - source_indexes: [lgpPduRcpEntryIndex]
        lookup: lgpPduRcpEntrySysAssignLabel
      - source_indexes: [lgpPduAuxSensorIndex]
        lookup: lgpPduAuxSensorSysAssignLabel

  liebert_pdu_cotto:
    walk:
      - sysName
      - sysDescr
      - sysUpTime
      - lgpPduTable
      - lgpPduPsTable
      - lgpPduPsLineTable
      - lgpPduRcpTable
      - lgpPduAuxSensorTable
      - lgpConditionsWellKnown
      - lgpEnvTemperatureWellKnown
    lookups:
      - source_indexes: [lgpPduEntryIndex]
        lookup: lgpPduEntrySysAssignLabel
      - source_indexes: [lgpPduPsEntryIndex]
        lookup: lgpPduPsEntrySysAssignLabel
      - source_indexes: [lgpPduRcpEntryIndex]
        lookup: lgpPduRcpEntrySysAssignLabel
      - source_indexes: [lgpPduAuxSensorIndex]
        lookup: lgpPduAuxSensorSysAssignLabel

  liebert_chiller:
    walk:
      - sysName
      - sysDescr
      - sysUpTime
      - lgpAgentManagedDeviceEntry
      - lgpEnvRemoteSensorTable
      - lgpEnvTemperatureTableDegC
      - lgpEnvTemperatureWellKnown
      - lgpEnvControlTemperature
      - lgpEnvHumidityTableRel
      - lgpAmbientTemperature
      - lgpConditionsWellKnown
      - lgpEnvTemperatureWellKnown
      - lgpEnvState
      - lgpFlexConditionsWellKnown
      - lgpConditionWaterUnderFloor
    lookups:
      - source_indexes: [lgpEnvRemoteSensorIndex]
        lookup: lgpEnvRemoteSensorUsrLabel

  liebert_gas_chiller:
    walk:
      - sysName
      - sysDescr
      - sysUpTime
      - sysLocation
      - lgpFlexibleBasicTable
      - lgpFlexibleExtendedTable
    lookups:
      - source_indexes: [lgpFlexibleEntryIndex]
        lookup: lgpFlexibleEntryDataLabel
      - source_indexes: [ifIndex]
        lookup: ifAlias

  liebert_ups:
    walk:
      - sysName
      - sysDescr
      - sysUpTime
      - lgpConditionsWellKnown
      - lgpPower
      - lgpNXC
      - upsInputFrequency
      - upsInputTable
    lookups:
      - source_indexes: [lgpEnvRemoteSensorIndex]
        lookup: lgpEnvRemoteSensorUsrLabel

  liebert_ups_vecchio:
    walk:
      - sysName
      - sysDescr
      - sysUpTime
      - luCore
    lookups:
      - source_indexes: [lgpEnvRemoteSensorIndex]
        lookup: lgpEnvRemoteSensorUsrLabel
